quicklogic: upstream fixes to PCF, SDC and post-synthesys
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>

diff --git a/quicklogic/common/toolchain_wrappers/ql_symbiflow b/quicklogic/common/toolchain_wrappers/ql_symbiflow
--- a/quicklogic/common/toolchain_wrappers/ql_symbiflow
+++ b/quicklogic/common/toolchain_wrappers/ql_symbiflow
@@ -477,9 +477,15 @@ else
 	JSON_PATH=""
 fi
 
+if [[ -f $SOURCE/$PCF ]];then
+	PCF_PATH=`realpath $SOURCE/$PCF`
+elif [[ -f $PCF ]];then
+	PCF_PATH=`realpath $PCF`
+fi
 
 export PART=${CSV_PATH}
 export JSON=${JSON_PATH}
+export PCF_PATH=${PCF_PATH}
 
 MAKE_FILE=${CURR_DIR}/Makefile.symbiflow
 LOG_FILE=${CURR_DIR}/${BUILDDIR}/${TOP}.log
@@ -491,17 +497,17 @@ else
     PCF_MAKE="\${current_dir}/build/${TOP}_dummy.pcf"
 fi
 
+PROCESS_SDC=`realpath ${MYPATH}/python/process_sdc_constraints.py`
 if ! [ -z "$SDC" ]; then
-	if ! [ -f "$SOURCE"/$SDC ];then
-            echo "The sdc file: $SDC is missing at: $SOURCE"
-            exit 1
-         else
-	    SDC_MAKE="\${current_dir}/$SDC"
-	    cp ${CURR_DIR}/$SDC ${CURR_DIR}/build/${TOP}.sdc
-         fi
+    if ! [ -f "$SOURCE"/$SDC ];then
+        echo "The sdc file: $SDC is missing at: $SOURCE"
+        exit 1
+    else
+        SDC_MAKE="$SOURCE/$SDC"
+    fi
 else
-  	 touch ${CURR_DIR}/build/${TOP}_dummy.sdc
-   	 SDC_MAKE="\${current_dir}/build/${TOP}_dummy.sdc"
+    touch ${CURR_DIR}/build/${TOP}_dummy.sdc
+    SDC_MAKE="\${current_dir}/build/${TOP}_dummy.sdc"
 fi
 
 echo -e ".PHONY:\${BUILDDIR}\n
@@ -516,8 +522,10 @@ FAMILY := $FAMILY\n\
 ANALYSIS_CORNER := $PNR_CORNER\n\
 PNR_CORNER := $ANALYSIS_CORNER\n\
 PCF := $PCF_MAKE\n\
-SDC := $SDC_MAKE\n\
+PINMAP_CSV := $CSV_PATH\n\
+SDC_IN := $SDC_MAKE\n\
 BUILDDIR := build\n\n\
+SDC := \${current_dir}/\${BUILDDIR}/\${TOP}.sdc
 
 all: \${BUILDDIR}/\${TOP}.bit\n\
 \n\
@@ -527,7 +535,9 @@ all: \${BUILDDIR}/\${TOP}.bit\n\
   endif\n\
 	cd \${BUILDDIR} && symbiflow_synth -t \${TOP} -v \${VERILOG} -f \${FAMILY} -d \${DEVICE} -p \${PCF} > $LOG_FILE 2>&1\n\
 \n\
-\${BUILDDIR}/\${TOP}.net: \${BUILDDIR}/\${TOP}.eblif\n\
+\${BUILDDIR}/\${TOP}.sdc: \${BUILDDIR}/\${TOP}.eblif\n\
+	python3 ${PROCESS_SDC} --sdc-in \${SDC_IN} --sdc-out \$@ --pcf \${PCF} --eblif \${BUILDDIR}/\${TOP}.eblif --pin-map \${PINMAP_CSV}\n\
+\${BUILDDIR}/\${TOP}.net: \${BUILDDIR}/\${TOP}.eblif \${BUILDDIR}/\${TOP}.sdc\n\
 	cd \${BUILDDIR} && symbiflow_pack -e \${TOP}.eblif -f \${FAMILY} -d \${DEVICE} -s \${SDC} -c \${PNR_CORNER} >> $LOG_FILE 2>&1\n\
 \n\
 \${BUILDDIR}/\${TOP}.place: \${BUILDDIR}/\${TOP}.net \${PCF}\n\
